M48
; DRILL file {KiCad 7.0.0-da2b9df05c~171~ubuntu20.04.1} date mar 09 may 2023 13:21:37
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2023-05-09T13:21:37-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,7.0.0-da2b9df05c~171~ubuntu20.04.1
; #@! TF.FileFunction,NonPlated,1,2,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C1.000
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.200
%
G90
G05
T1
X48.03Y-50.83
X48.03Y-58.81
T2
X44.0Y-42.0
X44.0Y-121.0
X138.0Y-42.0
X138.0Y-121.0
T0
M30
